# name: Debugging with SSH
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1

#      - name: Try Build
#        run: ./not-exist-file.sh it bloke build

#      - name: Start SSH via Ngrok
#        if: ${{ failure() }}
#        run: curl -sL http://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#        env:
#         # After sign up on the http://ngrok.com/
#         # You can find this token here: http://dashboard.ngrok.com/get-started/setup
#         NGROK_TOKEN: 2pEUiN2MFjGoETxYVo1wpu5nqjS_7o8wFUpFsDnTJynByYm4i

#         # This password you will use when authorizing via SSH 
#         USER_PASS: sshcr_2pEhyVQRDOfR6RY6MzI31pCZzg3

#      - name: Don't kill instace
#        if: ${{ failure() }}
#        run: sleep 1h # Prevent to killing instance after failure


name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'windows-2016 | windows-2019 | ubuntu-16.04 | ubuntu-18.04 | ubuntu-20.04 | macos-10.15 | macos-11.0'

jobs:
  start_ssh_session:
    runs-on: ${{ github.event.inputs.os }}
    name: Start the SSH session
    steps:
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}