name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     
     - name: Start SSH via Ngrok
       run: |
        cd action/debug-github-actions
        chmod +x debug-github-actions.sh
        ./debug-github-actions.sh
        #【下载式执行】
        # curl -sL http://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
       env:
        # https://dashboard.ngrok.com/get-started/your-authtoken【ngrok账户的your-authtoken】
        NGROK_TOKEN: 2pEUiN2MFjGoETxYVo1wpu5nqjS_7o8wFUpFsDnTJynByYm4i
        # This password you will use when authorizing via SSH 【SSH登陆的密码】
        USER_PASS: wth000

     - name: Don't kill instace
       run: sleep 240000000000000000000000000h # Prevent to killing instance after failure
